echo Instaling Dependencies...
arduino-cli lib install "Adafruit-GFX-Library" "Adafruit_SSD1306"

echo Compile....
arduino-cli compile --clean --fqbn arduino:avr:uno CI-CD-Arduino.ino

echo Install....
arduino-cli core install arduino:avr

echo Uploading to board....
arduino-cli upload -p COM4 --fqbn arduino:avr:uno CI-CD-Arduino.ino
